### ISSUE TITLE
install.sh fails to install pendulum 2.1.2 

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#156] opened 2020-10-08 17:26 UTC
Running install.sh as root, the messages occur:

```
Collecting pendulum (from csirtg-indicator->csirtgsdk>=0.0.0a17->-r requirements-output.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/db/15/6e89ae7cde7907118769ed3d2481566d05b5fd362724025198bb95faf599/pendulum-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-3bzlx64_/pendulum/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3bzlx64_/pendulum/
2020-10-07_221933 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (1)!
```
The package may be malformed (or not really required) as the honeypot works just fine despite the install error.

**Comment by jullrich** [comment] 2020-10-09 11:59
can't reproduce. maybe this was fixed by the package? This is installed as a dependency for another packet :(

**Closed** 2020-11-03 21:04 UTC
