### ISSUE TITLE
install.sh failure on initial install (still with us).

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#93] opened 2017-11-16 23:12 UTC
I tried a fresh install using 2017-09-07-raspbian-stretch-lite

The usual pw,hostname, ssh-enable, filesystem resize via raspi-config
then
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git
git clone https://github.com/DShield-ISC/dshield.git
cd dshield
sudo bin/install.sh

```
Collecting PyYAML<4.0,>=3.11 (from csirtgsdk>=0.0.0a6->-r requirements-output.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-11-16_220846 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-11-16_220846 ### Error installing dependencies from requirements-output.txt
```

Tried 'magic' fix:

sudo su -
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
pip install -r /srv/cowrie/requirements.txt
pip install -r /srv/cowrie/requirements-output.txt
exit
sudo bin/install.sh

and ran to completion.  "Houston, it's still a problem..."

**Comment by jullrich** [comment] 2017-11-17 00:54
ok I will try again. But this looks more and more like a problem in either urllib3 or "request" . But I think we may be able to catch the error, and maybe find a workaround. just hard without being able to replicate the problem.

thanks a lot for trying again.

**Comment by ktrue** [comment] 2017-12-04 19:13
Just tried (again) with a fresh-install of 2017-11-29-raspbian-stretch-lite.
Ran into the same issue again.  Performed the 'magic' fix, reran install.sh and got
```
Collecting botocore (from -r requirements-output.txt (line 20))
Exception:
Traceback (most recent call last):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-12-04_190955 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-12-04_190955 ### Error installing dependencies from requirements-output.txt. See /srv/log/install_2017-12-04_190529.log for details.
```
So now, even 'magic' doesn't work :(

**Comment by ktrue** [comment] 2017-12-13 17:59
Another try with 2017-11-29 Raspian stretch-lite results in
```
Collecting prettytable>=0.7.2 (from csirtgsdk>=0.0.0a17->-r requirements-output.txt (line 2))
  Downloading prettytable-0.7.2.zip
Collecting PyYAML<4.0,>=3.11 (from csirtgsdk>=0.0.0a17->-r requirements-output.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/srv/cowrie/cowrie-env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/srv/cowrie/cowrie-env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/srv/cowrie/cowrie-env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
2017-12-13_173712 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (2)!
2017-12-13_173712 ### Error installing dependencies from requirements-output.txt. See /srv/log/install_2017-12-13_171852.log for details.
```
Tried the 'magic-fix' 
```
sudo su -
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
pip install -r /srv/cowrie/requirements.txt
pip install -r /srv/cowrie/requirements-output.txt
exit
sudo bin/install.sh
```
and install.sh ran successfully to completion.  Maybe the cowrie dist has changed ?!?

**Comment by gebhard73** [comment] 2017-12-17 16:22
Sorry, could not reproduce.

Used Pi 3 with "Raspbian Stretch Lite" (https://www.raspberrypi.org/downloads/raspbian/) from 2017-11-29 and followed instructions (https://github.com/DShield-ISC/dshield) step by step.

Worked without further ado.

Don't know what goes wrong with pip in some cases.

--------8<----------------8<----------------8<----------------8<----------------8<--------
Collecting prettytable>=0.7.2 (from csirtgsdk>=0.0.0a17->-r requirements-output.txt (line 2))
  Downloading prettytable-0.7.2.zip
Collecting PyYAML<4.0,>=3.11 (from csirtgsdk>=0.0.0a17->-r requirements-output.txt (line 2))
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting tailer>=0.3 (from csirtgsdk>=0.0.0a17->-r requirements-output.txt (line 2))
--------8<----------------8<----------------8<----------------8<----------------8<--------

**Comment by gebhard73** [comment] 2017-12-17 19:10
OK, got a similar error during an update of an older installation, but 
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
solved it.

Will document it in README - as long as I have no idea how to reliable reproduce (only during update, not during clean re-install) and how catch in install.sh ...

**Comment by ktrue** [comment] 2017-12-18 18:12
I did a clean install on a RPi2B this morning.  Died as I'd seen before in the install.
Ran the 
pip freeze --local | grep -v '^-e' | cut -d = -f 1 | xargs -n1 pip install -U
as root, and it died again in install.sh at a different place.
Had to run the rest of the 'magic' as root:

pip install -r /srv/cowrie/requirements.txt
pip install -r /srv/cowrie/requirements-output.txt

then the install.sh would complete successfully.  Maybe it's a RPi2B v.s. RPi3B issue??

anyway, I'm not closing this just yet as it is persistent on my RPi2B.

**Comment by jullrich** [comment] 2017-12-18 19:00
I think I got a Pi2B somewhere. Will see if I can reproduce. This could be an issue with not enough memory. How much RAM do you have?

On Dec 18, 2017, at 1:12 PM, Ken <notifications@github.com<mailto:notifications@github.com>> wrote:


I did a clean install on a RPi2B this morning. Died as I'd seen before in the install.
Ran the
pip freeze --local | grep -v '^-e' | cut -d = -f 1 | xargs -n1 pip install -U
as root, and it died again in install.sh at a different place.
Had to run the rest of the 'magic' as root:

pip install -r /srv/cowrie/requirements.txt
pip install -r /srv/cowrie/requirements-output.txt

then the install.sh would complete successfully. Maybe it's a RPi2B v.s. RPi3B issue??

anyway, I'm not closing this just yet as it is persistent on my RPi2B.

**Comment by jullrich** [comment] 2018-05-18 20:14
closing this again. I installed several times today on a Pi 3B+ and never ran into this error.

**Closed by jullrich** 2018-05-18 20:14 UTC
